data_path: to_share/data
model: fragment-adjacency-predictor
run_name: multitask_02_seed_1
notes: multi-task lambda_same=0.2 (cond d)
n_images: 10
max_iterations: 25000
eval_every: 250
patience: 10
beta: 0.01923
lambda_adj: 1.0
lambda_same: 0.2
n_eval_batches: 20
balanced_clustering: true
seed: 1
